#ifndef _MATERIAL_PROPS_
#define _MATERIAL_PROPS_

#define WOOD_STATIC_FRICTION 0.5f
#define WOOD_DYNAMIC_FRICTION 0.3f
#define WOOD_RESTITUTION 0.603f

#define HOLLOWPVC_STATIC_FRICTION 0.5f
#define HOLLOWPVC_DYNAMIC_FRICTION 0.3f
#define HOLLOWPVC_RESTITUTION 0.688f

#define SOLIDPVC_STATIC_FRICTION 0.5f
#define SOLIDPVC_DYNAMIC_FRICTION 0.3f
#define SOLIDPVC_RESTITUTION 0.804f

#define HOLLOWSTEEL_STATIC_FRICTION 0.5f
#define HOLLOWSTEEL_DYNAMIC_FRICTION 0.3f
#define HOLLOWSTEEL_RESTITUTION 0.449f

#define SOLIDSTEEL_STATIC_FRICTION 0.5f
#define SOLIDSTEEL_DYNAMIC_FRICTION 0.3f
#define SOLIDSTEEL_RESTITUTION 0.597f

#define CONCRETE_STATIC_FRICTION 0.5f
#define CONCRETE_DYNAMIC_FRICTION 0.3f
#define CONCRETE_RESTITUTION 0.25f

#endif